version: '3'

services:
    ms-chat:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        command: npm run dev
        ports:
            - 6000:6000
        volumes:
            - ./src:/api/src
            - ./package.json:/api/package.json
            - ./.env.development:/api/.env.development
        depends_on:
            - mongo
            - redis
        networks:
            - server_network
            - ms-auth_server_network

    redis:
        image: bitnami/redis
        restart: unless-stopped
        environment:
            - REDIS_PASSWORD=password123
        ports:
            - 26379:6379
        networks:
            - server_network

    mongo:
        image: mongo
        restart: unless-stopped
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=master
            - MONGO_INITDB_ROOT_PASSWORD=password123
        networks:
            - server_network

    mongo-express:
        image: mongo-express
        restart: unless-stopped
        ports:
            - 28081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=master
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
        networks:
            - server_network

networks:
    server_network:
        driver: bridge
    ms-auth_server_network:
        external: true
